# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brian
tagline:          'I am a person who does things.'
description:      'I do things.'
url:              https://brianporeilly.github.io
baseurl:          /

author:
  name:           Brian P O'Reilly
  url:            https://brianporeilly.com

paginate:         5

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

github:
  repo: https://github.com/brianporeilly/brianporeilly.github.io
