version: "3.8"
services:
  site:
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    ports:
      - 4000:4000
    command: jekyll serve --livereload

volumes:
  bundle: {}